### ISSUE TITLE
Module not found error: ros2_aruco_interfaces

### ISSUE THREAD

**Issue by jeeveshreddy** [SimonGiampy/ros2-aruco-pose-estimation#1]
Hi,

The aruco detection and pose arrys works fine, but there is no visualization/data from the /aruco_markers and if I do topic echo it states as the 'ModuleNotFoundError: No module name7d 'ros2_aruco_interfaces". 

But there is a ros2_interfaces directory with required messages with successful build and it is sourced.

Can please suggest a way to fix this?

![Screenshot from 2023-12-12 14-03-23](https://github.com/SimonGiampy/ros2-aruco-pose-estimation/assets/129860370/2b63f0f0-3adc-4049-a1bb-a32f5a2f21c5)

Thanks
Jeevesh

**Comment by SimonGiampy** [comment]
Hello and thanks for trying out my code! Your error seems to be originated from a missing source command or an error in the building of the package `ros2_aruco_interfaces`. I checked again and didn't find any compilation error in my source code, maybe you changed some parameter or package name and cannot find the folder? Did you write `source install/setup.bash` in your ros2 workspace? 

Here there is a screenshot of your commands with the code correctly compiled. Note that the topic echo works but is empty since I'm not showing any aruco marker to the camera right now.

![image](https://github.com/SimonGiampy/ros2-aruco-pose-estimation/assets/13204484/0c41a09f-8f87-4bee-b7b1-f91d91be07aa)

**Comment by jeeveshreddy** [comment]
@SimonGiampy 
Thank you so much.
It's working now! The problem was with sourcing on a particular terminal.

![Screenshot from 2024-01-01 11-40-19](https://github.com/SimonGiampy/ros2-aruco-pose-estimation/assets/129860370/e8a6746e-36f4-4e86-88ea-ea58aeb9d007)

Jeevesh
